config/routes.rb
Rails.application.routes.draw do
    root "sessions#home"

    get '/signup' => 'users#new', as: 'signup'
    post '/signup' => 'users#create'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'

    delete '/logout' => 'sessions#destroy'

    post 'plants/search' => 'plants#search', as: 'plants_search'

    resources :users
    resources :plants
    resources :gardens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_and_belongs_to_many :gardens
    has_many :users, through: :gardens


    def self.results_mapper(results)
        all_mapped_results = results["data"].map do |p|
            mapped_results = {}
            mapped_results[:common_name] = p["common_name"]
            mapped_results[:scientific_name] = p["scientific_name"] 
            mapped_results[:id] = p["id"]
            mapped_results
        end 
        return all_mapped_results
    end

    def self.find_or_create(api_id)
    end

    def self.new_from_hash(hash)
        p = Plant.new
        p.common_name = hash[:common_name]
        p.scientific_name = hash[:scientific_name]
        p.api_id = hash[:id]
        p
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gardens
    has_many :plants, through: :gardens

    validates :email,
    format: { with: /\A(\S+)@(.+)\.(\S+)\z/, message: "Email invalid"  },
            uniqueness: { case_sensitive: false },
            length: { minimum: 4, maximum: 254 }  
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?

    private

    def log_in(user)
        session[:user_id] = user.id 
    end 

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end 
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

    def index
    end

    def show
    end

    def new
    end

    def create
    end
    
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    def index
    end

    def show
    end

    def new
    end

    def create
        user = current_user
        plant = Plant.find_or_create_by(params[:plant_id])
    end

    def search
        @name = params[:name]
        @search = Trefle::Adapter.search(params[:name])

        @temp = @search.map do |p|
            Plant.new_from_hash(p)
        end  
        render :index 
    end

    def destroy
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def destroy
        session.clear
        redirect_to root_path
    end
    
    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
          flash[:message] = "Incorrect login info, please try again"
          redirect_to "/login"
        end
    end
      
    private

    def auth
      request.env['omniauth.auth']
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            log_in(@user)
            redirect_to user_path(@user)
        else 
            flash.now[:danger] = @user.errors.full_messages
            render :new 
        end 
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private 

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gardens/index.html.erb
<h1>Index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garden Builder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="border"></div>

    <div class="header">
        <h1>Garden Builder</h1>
        <p></p>
    </div>

    <div class="topnav">
    <li id="search_partial"> <%= render '/search_plants'%>
        <%= link_to "Home", '/' %>
        <%= link_to "Plants", plants_path %>
        <%= link_to "Gardens", '/' %>
        <% if logged_in?%>
            <%= link_to "Profile", '/' %>
        <% else %>
            <%=link_to "Sign Up", signup_path %> |
            <%=link_to "Log In", login_path %>
        <% end %>
    </div>

    <div>
      <% if flash[:message] %>
          <%= flash[:message]%>

      <% end %>
      <%= @error%>
    </div>  
    <%= yield %>

    <div class="content">
    </div>

    <div class="footer">
        <h2>Garden Builder 2021</h2>
    </div>

  </body>
</html>

app/views/plants/index.html.erb
<div class="container">
<h2>Search results for "<%= @name%>":</h2>

<div class="card-wrapper"> 
<% @temp.each do |p| %>
        <div class="card">
        <h3>Common Name</h3> <%= p.common_name %><br>
        <h3>Scientific Name</h3> <%= p.scientific_name %><br>
        

        
        </div>
<%end%>

</div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
    <%= f.text_field :email, placeholder: "email", class: 'form-control' %>
    <%= f.password_field :password, placeholder: "password", class: 'form-control' %>
    <%= f.submit "#{button_name}", class: "btn btn-primary" %>
<%end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%# render partial: "layouts/errors", locals: {object: @user} %>


<%= render 'form', {button_name: "Sign Up!"} %>

app/views/users/show.html.erb
<h1>Show <%=@user.email %></h1>